---
title: R-Universe
page-layout: full
toc: true
---

## Introduction

The MRC IEU R-universe <https://mrcieu.r-universe.dev> distributes binary R packages for many MR related packages which are currently only available on GitHub and have to be installed from source. Especially on Linux, installing packages from source can be very slow. The binary packages are available for several operating systems; Windows, macOS with Intel processors, and Ubuntu Linux 22.04 Jammy Jellyfish (and more will be available as the R-universe system extends).

If you would like a package added to the universe please open an issue in our [repository](https://github.com/MRCIEU/mrcieu.r-universe.dev/issues).

Additionally, each package included in the R-Universe has its own webpages, meaning you can read the rendered vignettes, which is helpful if a package does not have its own website, e.g.,

* [the R-Universe webpage for **TwoSampleMR**](https://mrcieu.r-universe.dev/TwoSampleMR)
* [and its exposure data vignette](https://mrcieu.r-universe.dev/articles/TwoSampleMR/exposure.html)

## How to install binary R packages from the MRC IEU R-universe

To install binary R packages from the MRC IEU R-universe, include the URL in your `repos` list as shown below.

### Windows and Intel Mac users

For Windows and Intel Mac users to install the binary version of **TwoSampleMR**, run the following code.

```r
# Installation code for Windows and Intel Mac users
install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev',
    'https://cloud.r-project.org'
  )
)
```

### Ubuntu Linux users

For Ubuntu Linux Jammy Jellyfish users running R through RStudio Desktop or RStudio Server, to install **TwoSampleMR** run the following code.

```r
# Installation code for Ubuntu Jammy Jellyfish users in RStudio Desktop or Server
install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)
```

For Ubuntu Linux Jammy Jellyfish users running R in the Terminal first amend the `HTTPUserAgent` option,[^1] and then run the Linux installation code above. If the `HTTPUserAgent` option is not amended it seems that source rather than binary packages are obtained for the Imports dependency packages from the Posit Public Package Manager's CRAN packages. For this case, to install **TwoSampleMR**, run the following code.

[^1]: As described in the following blog [post](https://tshafer.com/blog/2023/07/posit-package-manager-linux).

```r
# Installation code for Ubuntu Jammy Jellyfish users running R in the Terminal
options(HTTPUserAgent = sprintf(
  "R/%s R (%s)",
  getRversion(),
  paste(getRversion(),
        R.version["platform"],
        R.version["arch"],
        R.version["os"])
))

install.packages(
  'TwoSampleMR',
  repos = c(
    'https://mrcieu.r-universe.dev/bin/linux/jammy/4.3/',
    'https://packagemanager.posit.co/cran/__linux__/jammy/latest',
    'https://cloud.r-project.org'
  )
)
```

### WebR users

WASM binaries for WebR users are available with the code below. Note that currently not all packages are available for WebR.

```r
install.packages('TwoSampleMR',
  repos = c('https://mrcieu.r-universe.dev', 'https://repo.r-wasm.org'))
```
